name: YouTube View Tracker

on:
  schedule:
    - cron: "* * * * *"

  workflow_dispatch:


permissions:
  contents: write


jobs:
  track:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Install dependencies
      run: |
        pip install requests


    - name: Run Tracker
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        python tracker/track_views.py


    - name: Commit Database Update
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        git add database/youtube.db

        git commit -m "Update YouTube views" || echo "No changes"

        git push